version: '3'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: eldrige
      POSTGRES_PASSWORD: kendrick7
      POSTGRES_DB: easygo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: easy-go-app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: 'postgresql://eldrige:kendrick7@postgres:5432/easygo'
    ports:
      - '2000:2000'
    volumes:
      - .:/usr/src/app
    command: ['sh', '-c', 'npx prisma migrate deploy && npx nodemon server.js']

volumes:
  postgres_data:
