name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            peldrige/easy-go:latest
            peldrige/easy-go:${{ github.sha }}

      - name: Deploy to web-01
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.AWS_EC2_IP_ADDRESS }}
          username: ${{ secrets.AWS_HOST_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd app || exit 1
            echo "Pulling latest image..."
            if ! sudo docker pull peldrige/easy-go:latest; then
              echo "Failed to pull image"
              exit 1
            fi
            echo "Stopping current services..."
            if ! sudo docker compose down; then
              echo "Warning: Failed to bring services down cleanly"
            fi
            echo "Starting new services..."
            if ! sudo docker compose up -d --force-recreate; then
              echo "Failed to start services"
              exit 1
            fi
            echo "Cleaning up unused resources..."
            sudo docker system prune -f
            echo "Deployment completed successfully"
