name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: peldrige/easy-go:latest

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.AWS_EC2_IP_ADDRESS }}
          username: ${{ secrets.AWS_HOST_USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker pull peldrige/easy-go:latest
            sudo docker-compose down
            sudo docker-compose up -d --force-recreate
            sudo docker system prune -f
            echo "Checking if easy-go is running..."
            sleep 5
            if sudo docker ps --filter "name=easy-go" --filter "status=running" | grep easy-go; then
              echo "✅ easy-go is running!"
            else
              echo "❌ easy-go failed to start!"
              sudo docker logs easy-go
              exit 1
            fi
